sonar.projectKey=adp-vat
sonar.projectName=adp-vat
sonar.sources=.
sonar.tests=src/test/java
sonar.java.source=8
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports
sonar.sourceEncoding=UTF-8
