sonar.projectKey=vat-processing-service
sonar.projectName=VAT Processing Service
sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.source=8
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports,target/failsafe-reports
sonar.sourceEncoding=UTF-8
